### ISSUE TITLE
How do I use this with nvim-treesitter?

### ISSUE THREAD

**Issue by samrath2007** [victorhqc/tree-sitter-prisma#27]

**Comment by victorhqc** [comment]
Good question! Unfortunately, I don't have an answer for that. Have you checked the tree-sitter documentation about it? This package only provides a generic parser, which I used to give Atom syntax highlighting.

Giving a quick glance on [the docs](https://github.com/nvim-treesitter/nvim-treesitter) it seems that it should be fairly easy to do, you'll have to make your own package that uses this to do so.

My advice would be to look at the docs, and try to find an example package that uses a tree sitter parser like this one 😄 good luck! 🙌

**Comment by samrath2007** [comment]
Thank you!

**Comment by victorhqc** [comment]
Let me know if I can help in any way :)
