### ISSUE TITLE
Support composite types syntax

### ISSUE THREAD

**Issue by aqrln** [victorhqc/tree-sitter-prisma#32]
Since Prisma 3.10.0, there's a new syntax for composite types, currently used for embedded documents in MongoDB: https://www.prisma.io/docs/concepts/components/prisma-client/composite-types

**Comment by victorhqc** [comment]
Thank you for reporting this, I'll give it a look 👍

**Comment by aqrln** [comment]
Thank you!

**Comment by victorhqc** [comment]
Added support for the composite types. Not sure if neovim is properly supported, but I'm happy to receive a PR to address it if there's any issue. Thanks again for the notice of the new feature :)

**Comment by aqrln** [comment]
The only thing missing for neovim was the highlighting of the `type` keyword, fixed here: https://github.com/nvim-treesitter/nvim-treesitter/pull/2671. I noticed there's a `highlights.scm` file here in this repo too (and it looks outdated compared to the one in `nvim-treesitter` repo even besides the `type` keyword change, I think it corresponds to what used to be in the `nvim-treesitter` repo [in this commit](https://github.com/aqrln/nvim-treesitter/commit/b2801abc21a37fde34e92c520e365d4ec652afe4)), is it actually used for anything? I'm not sure because I'm new to the treesitter ecosystem and I still have quite fuzzy understanding of how things work.
