### ISSUE TITLE
Segmentation fault with helix when trying paste yanked first column_declaration

### ISSUE THREAD

**Issue by seshotake** [victorhqc/tree-sitter-prisma#38]
This issue is similiar to victorhqc/tree-sitter-prisma#34. 

I were trying to edit the prisma file with master branch and noticed that helix crashes and return segfault when I yank the first column declaration and try to paste in the end file.

**Comment by victorhqc** [comment]
There's a PR ready for it, could you help me verify the issue? I wrote some tests that reproduced the error, but I want to be sure that there are no more segmentation faults

**Comment by seshotake** [comment]
Sure, I will try it and report soon. Sorry for delay

**Comment by seshotake** [comment]
I did some tests like this: 

```prisma
model User {
  id Int @id @default(autoincrement())
}
```

yanked this line and trying paste in the end of file. It seems everything is good. I don't have  segfault anymore. Thank you for your work in resolving the problem!

**Comment by victorhqc** [comment]
Perfect! Then I'll make a new release!
